openapi: 3.0.0
info:
  title: Server Browser API
  version: 1.0.0
servers:
- url: /
paths:
  /api/v1/swagger.yaml:
    get:
      responses:
        "200":
          content:
            text/yaml:
              schema:
                type: string
          description: Successful operation
      summary: Get the swagger documentation
  /api/v1/servers:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerListResponse"
          description: Successful operation
      summary: Get a list of registered game servers.
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ServerRegistrationRequest"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegistrationResponse"
          description: Successful operation
      summary: Register a game server
  /api/v1/servers/{unique_id}:
    delete:
      parameters:
      - description: The key provided at registration time
        explode: false
        in: header
        name: X-CHIV2-SERVER-BROWSER-KEY
        required: true
        schema:
          type: string
        style: simple
      - description: The unique id of the server being updated
        explode: false
        in: path
        name: unique_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
          description: Something in your request is malformed
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
          description: Server not registered
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
          description: Invalid key provided
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
          description: Successful operation
      summary: Remove the listing for a game server.
    put:
      parameters:
      - description: The key provided at registration time
        explode: false
        in: header
        name: X-CHIV2-SERVER-BROWSER-KEY
        required: true
        schema:
          type: string
        style: simple
      - description: The unique id of the server being updated
        explode: false
        in: path
        name: unique_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateRegisteredServer"
        required: true
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
          description: Something in your request is malformed
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
          description: You did something you're not allowed to do with the parameters
            provided.
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
          description: Server not registered
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateResponse"
          description: Successful operation
      summary: Update the listing for a game server. This does not count as a heartbeat
  /api/v1/servers/{unique_id}/heartbeat:
    post:
      parameters:
      - description: The key provided at registration time
        explode: false
        in: header
        name: X-CHIV2-SERVER-BROWSER-KEY
        required: true
        schema:
          type: string
        style: simple
      - description: The unique id of the server being updated
        explode: false
        in: path
        name: unique_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
          description: Something in your request is malformed
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
          description: You did something you're not allowed to do with the parameters
            provided.
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
          description: Server not registered
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateResponse"
          description: Successful operation
      summary: Send a keepalive signal to stay on the server list
  /api/v1/check-banned/{ip}:
    get:
      parameters:
      - description: The IP address to check
        explode: false
        in: path
        name: ip
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BanStatusResponse"
          description: Successful operation
      summary: Check if an IP address is banned
  /api/v1/admin/ban-list:
    delete:
      parameters:
      - description: The admin key
        explode: false
        in: header
        name: X-CHIV2-SERVER-BROWSER-ADMIN-KEY
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IpListRequest"
        required: true
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
          description: Invalid admin key
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BanListResponse"
          description: Successful operation
      summary: Remove IP addresses from the ban list
    get:
      parameters:
      - description: The admin key
        explode: false
        in: header
        name: X-CHIV2-SERVER-BROWSER-ADMIN-KEY
        required: true
        schema:
          type: string
        style: simple
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
          description: Invalid admin key
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BanListResponse"
          description: Successful operation
      summary: Get the list of banned IP addresses
    put:
      parameters:
      - description: The admin key
        explode: false
        in: header
        name: X-CHIV2-SERVER-BROWSER-ADMIN-KEY
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IpListRequest"
        required: true
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
          description: Invalid IP address
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
          description: Invalid admin key
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BanListResponse"
          description: Successful operation
      summary: Add IP addresses to the ban list
  /api/v1/admin/verified-list:
    delete:
      parameters:
      - description: The admin key
        explode: false
        in: header
        name: X-CHIV2-SERVER-BROWSER-ADMIN-KEY
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IpListRequest"
        required: true
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
          description: Invalid admin key
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerifiedListResponse"
          description: Successful operation
      summary: Remove IP addresses from the verified list
    get:
      parameters:
      - description: The admin key
        explode: false
        in: header
        name: X-CHIV2-SERVER-BROWSER-ADMIN-KEY
        required: true
        schema:
          type: string
        style: simple
      responses:
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
          description: Invalid admin key
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerifiedListResponse"
          description: Successful operation
      summary: Get the list of verified IP addresses
    put:
      parameters:
      - description: The admin key
        explode: false
        in: header
        name: X-CHIV2-SERVER-BROWSER-ADMIN-KEY
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IpListRequest"
        required: true
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
          description: Invalid IP address
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
          description: Invalid admin key
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerifiedListResponse"
          description: Successful operation
      summary: Add IP addresses to the verified list
  /api/tbio/GetCurrentGames:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TbioServerListResponse"
          description: Successful operation
      summary: Get a list of servers in Chivalry 2 format
  /api/tbio/GetMotd:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MotdRequest"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TbioMotdResponse"
          description: Successful operation
      summary: Get the Message of the Day
  /api/playfab/Client/Matchmake:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/_api_playfab_Client_Matchmake_post_request"
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlayfabErrorResponse"
          description: No LobbyId provided
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlayfabErrorResponse"
          description: Lobby does not exist
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlayfabMatchmakeResponse"
          description: Successful operation
      summary: Matchmake a client to a server
components:
  schemas:
    TbioServerListResponse:
      example:
        Data:
          Games:
          - LastHeartbeat: 2
            RunTime: 5
            LobbyId: LobbyId
            MaxPlayers: 1
            GameMode: GameMode
            GameServerState: 5
            PlayerUserIds:
            - PlayerUserIds
            - PlayerUserIds
            Official: true
            ServerHostname: ServerHostname
            Region: Region
            BuildVersion: BuildVersion
            ServerIPV4Address: ServerIPV4Address
            Tags:
              PingPort_i: PingPort_i
              T0_c: T0_c
              QueryPort_i: QueryPort_i
              ServerName_s: ServerName_s
              Platform_s: Platform_s
              MTIM_i: MTIM_i
              MS_i: MS_i
              t1_c: t1_c
              BuildId_s: BuildId_s
              pp_b: pp_b
              Region_s: Region_s
              MapName_s: MapName_s
              OFFICIAL_b: OFFICIAL_b
              FFA_b: FFA_b
            ServerPort: 7
          - LastHeartbeat: 2
            RunTime: 5
            LobbyId: LobbyId
            MaxPlayers: 1
            GameMode: GameMode
            GameServerState: 5
            PlayerUserIds:
            - PlayerUserIds
            - PlayerUserIds
            Official: true
            ServerHostname: ServerHostname
            Region: Region
            BuildVersion: BuildVersion
            ServerIPV4Address: ServerIPV4Address
            Tags:
              PingPort_i: PingPort_i
              T0_c: T0_c
              QueryPort_i: QueryPort_i
              ServerName_s: ServerName_s
              Platform_s: Platform_s
              MTIM_i: MTIM_i
              MS_i: MS_i
              t1_c: t1_c
              BuildId_s: BuildId_s
              pp_b: pp_b
              Region_s: Region_s
              MapName_s: MapName_s
              OFFICIAL_b: OFFICIAL_b
              FFA_b: FFA_b
            ServerPort: 7
          GameCount: 0
          PlayerCount: 6
        Success: true
      properties:
        Success:
          type: boolean
        Data:
          $ref: "#/components/schemas/TbioServerListData"
      type: object
    TbioServerListData:
      example:
        Games:
        - LastHeartbeat: 2
          RunTime: 5
          LobbyId: LobbyId
          MaxPlayers: 1
          GameMode: GameMode
          GameServerState: 5
          PlayerUserIds:
          - PlayerUserIds
          - PlayerUserIds
          Official: true
          ServerHostname: ServerHostname
          Region: Region
          BuildVersion: BuildVersion
          ServerIPV4Address: ServerIPV4Address
          Tags:
            PingPort_i: PingPort_i
            T0_c: T0_c
            QueryPort_i: QueryPort_i
            ServerName_s: ServerName_s
            Platform_s: Platform_s
            MTIM_i: MTIM_i
            MS_i: MS_i
            t1_c: t1_c
            BuildId_s: BuildId_s
            pp_b: pp_b
            Region_s: Region_s
            MapName_s: MapName_s
            OFFICIAL_b: OFFICIAL_b
            FFA_b: FFA_b
          ServerPort: 7
        - LastHeartbeat: 2
          RunTime: 5
          LobbyId: LobbyId
          MaxPlayers: 1
          GameMode: GameMode
          GameServerState: 5
          PlayerUserIds:
          - PlayerUserIds
          - PlayerUserIds
          Official: true
          ServerHostname: ServerHostname
          Region: Region
          BuildVersion: BuildVersion
          ServerIPV4Address: ServerIPV4Address
          Tags:
            PingPort_i: PingPort_i
            T0_c: T0_c
            QueryPort_i: QueryPort_i
            ServerName_s: ServerName_s
            Platform_s: Platform_s
            MTIM_i: MTIM_i
            MS_i: MS_i
            t1_c: t1_c
            BuildId_s: BuildId_s
            pp_b: pp_b
            Region_s: Region_s
            MapName_s: MapName_s
            OFFICIAL_b: OFFICIAL_b
            FFA_b: FFA_b
          ServerPort: 7
        GameCount: 0
        PlayerCount: 6
      properties:
        GameCount:
          type: integer
        PlayerCount:
          type: integer
        Games:
          items:
            $ref: "#/components/schemas/TbioGame"
          type: array
      type: object
    TbioGame:
      example:
        LastHeartbeat: 2
        RunTime: 5
        LobbyId: LobbyId
        MaxPlayers: 1
        GameMode: GameMode
        GameServerState: 5
        PlayerUserIds:
        - PlayerUserIds
        - PlayerUserIds
        Official: true
        ServerHostname: ServerHostname
        Region: Region
        BuildVersion: BuildVersion
        ServerIPV4Address: ServerIPV4Address
        Tags:
          PingPort_i: PingPort_i
          T0_c: T0_c
          QueryPort_i: QueryPort_i
          ServerName_s: ServerName_s
          Platform_s: Platform_s
          MTIM_i: MTIM_i
          MS_i: MS_i
          t1_c: t1_c
          BuildId_s: BuildId_s
          pp_b: pp_b
          Region_s: Region_s
          MapName_s: MapName_s
          OFFICIAL_b: OFFICIAL_b
          FFA_b: FFA_b
        ServerPort: 7
      properties:
        Region:
          type: string
        LobbyId:
          type: string
        MaxPlayers:
          type: integer
        Official:
          type: boolean
        BuildVersion:
          type: string
        GameMode:
          type: string
        PlayerUserIds:
          items:
            type: string
          type: array
        RunTime:
          type: integer
        GameServerState:
          type: integer
        Tags:
          $ref: "#/components/schemas/TbioTags"
        LastHeartbeat:
          type: integer
        ServerHostname:
          type: string
        ServerIPV4Address:
          type: string
        ServerPort:
          type: integer
      type: object
    TbioTags:
      example:
        PingPort_i: PingPort_i
        T0_c: T0_c
        QueryPort_i: QueryPort_i
        ServerName_s: ServerName_s
        Platform_s: Platform_s
        MTIM_i: MTIM_i
        MS_i: MS_i
        t1_c: t1_c
        BuildId_s: BuildId_s
        pp_b: pp_b
        Region_s: Region_s
        MapName_s: MapName_s
        OFFICIAL_b: OFFICIAL_b
        FFA_b: FFA_b
      properties:
        BuildId_s:
          type: string
        ServerName_s:
          type: string
        Region_s:
          type: string
        OFFICIAL_b:
          type: string
        Platform_s:
          type: string
        FFA_b:
          type: string
        MS_i:
          type: string
        MapName_s:
          type: string
        PingPort_i:
          type: string
        QueryPort_i:
          type: string
        T0_c:
          type: string
        pp_b:
          type: string
        t1_c:
          type: string
        MTIM_i:
          type: string
      type: object
    TbioMotdResponse:
      example:
        Data: "{}"
        expiration: 0
        Success: true
      properties:
        Success:
          type: boolean
        Data:
          type: object
        expiration:
          type: integer
      type: object
    PlayfabMatchmakeResponse:
      example:
        code: 6
        data:
          Ticket: Ticket
          ServerHostname: ServerHostname
          ServerIPV4Address: ServerIPV4Address
          ServerPort: 1
        status: status
      properties:
        code:
          type: integer
        status:
          type: string
        data:
          $ref: "#/components/schemas/PlayfabGame"
      type: object
    PlayfabGame:
      example:
        Ticket: Ticket
        ServerHostname: ServerHostname
        ServerIPV4Address: ServerIPV4Address
        ServerPort: 1
      properties:
        ServerHostname:
          type: string
        ServerIPV4Address:
          type: string
        ServerPort:
          type: integer
        Ticket:
          type: string
      type: object
    PlayfabErrorResponse:
      example:
        code: 0
        data: "{}"
        success: true
        message: message
        params: "{}"
      properties:
        code:
          type: integer
        data:
          type: object
        message:
          type: string
        params:
          type: object
        success:
          type: boolean
      type: object
    UpdateRegisteredServer:
      example:
        player_count: 0
        max_players: 6
        current_map: current_map
      properties:
        player_count:
          description: The number of players currently on the server
          format: int32
          type: integer
        max_players:
          description: The max number of players the server allows
          format: int32
          type: integer
        current_map:
          description: The current map being played on the server
          type: string
      required:
      - current_map
      - max_players
      - player_count
      type: object
    Mod:
      example:
        organization: organization
        name: name
        version: version
      properties:
        name:
          description: The name of the mod
          type: string
        organization:
          description: The organization that provides the mod
          type: string
        version:
          description: The version of the mod
          type: string
      required:
      - name
      - organization
      - version
      type: object
    ServerListResponse:
      example:
        servers:
        - player_count: 5
          mods:
          - organization: organization
            name: name
            version: version
          - organization: organization
            name: name
            version: version
          unique_id: unique_id
          password_protected: true
          name: name
          description: description
          max_players: 5
          ports:
            game: 0
            a2s: 6
            ping: 1
          last_heartbeat: 2.3021358869347655
          is_verified: true
          current_map: current_map
        - player_count: 5
          mods:
          - organization: organization
            name: name
            version: version
          - organization: organization
            name: name
            version: version
          unique_id: unique_id
          password_protected: true
          name: name
          description: description
          max_players: 5
          ports:
            game: 0
            a2s: 6
            ping: 1
          last_heartbeat: 2.3021358869347655
          is_verified: true
          current_map: current_map
      properties:
        servers:
          description: A list of servers
          items:
            $ref: "#/components/schemas/ServerResponse"
          type: array
      required:
      - servers
      type: object
    ServerResponse:
      example:
        player_count: 5
        mods:
        - organization: organization
          name: name
          version: version
        - organization: organization
          name: name
          version: version
        unique_id: unique_id
        password_protected: true
        name: name
        description: description
        max_players: 5
        ports:
          game: 0
          a2s: 6
          ping: 1
        last_heartbeat: 2.3021358869347655
        is_verified: true
        current_map: current_map
      properties:
        unique_id:
          description: The unique identifier of this server
          type: string
        ports:
          $ref: "#/components/schemas/Chivalry2Ports"
        password_protected:
          description: Whether the server is password protected
          type: boolean
        is_verified:
          description: Whether the server is verified
          type: boolean
        name:
          description: The name of the server
          type: string
        description:
          description: A description of the server
          type: string
        current_map:
          description: The current map being played on the server
          type: string
        player_count:
          description: The number of players currently on the server
          format: int32
          type: integer
        max_players:
          description: The max number of players on the server
          format: int32
          type: integer
        mods:
          description: A list of mods running on the server
          items:
            $ref: "#/components/schemas/Mod"
          type: array
        last_heartbeat:
          description: Unix timestamp of the last heartbeat
          format: double
          type: number
      required:
      - current_map
      - description
      - is_verified
      - last_heartbeat
      - max_players
      - mods
      - name
      - password_protected
      - player_count
      - ports
      - unique_id
      type: object
    ServerRegistrationRequest:
      example:
        player_count: 0
        mods:
        - organization: organization
          name: name
          version: version
        - organization: organization
          name: name
          version: version
        password_protected: true
        name: name
        description: description
        max_players: 6
        ports:
          game: 0
          a2s: 6
          ping: 1
        current_map: current_map
        local_ip_address: local_ip_address
      properties:
        ports:
          $ref: "#/components/schemas/Chivalry2Ports"
        name:
          description: The name of the server
          type: string
        description:
          description: A description of the server
          type: string
        current_map:
          description: The current map being played on the server
          type: string
        player_count:
          description: The number of players currently on the server
          format: int32
          type: integer
        max_players:
          description: The max number of players on the server
          format: int32
          type: integer
        password_protected:
          description: Whether the server is password protected
          type: boolean
        mods:
          description: A list of mods running on the server
          items:
            $ref: "#/components/schemas/Mod"
          type: array
        local_ip_address:
          description: The local IP address of the server
          type: string
      required:
      - current_map
      - description
      - max_players
      - mods
      - name
      - password_protected
      - player_count
      - ports
      type: object
    RegistrationResponse:
      example:
        server:
          player_count: 5
          mods:
          - organization: organization
            name: name
            version: version
          - organization: organization
            name: name
            version: version
          unique_id: unique_id
          password_protected: true
          name: name
          description: description
          max_players: 5
          ports:
            game: 0
            a2s: 6
            ping: 1
          last_heartbeat: 2.3021358869347655
          is_verified: true
          current_map: current_map
        refresh_before: 0.8008281904610115
        key: key
      properties:
        key:
          description: To be used as the X-CHIV2-SERVER-BROWSER-KEY header
          type: string
        refresh_before:
          description: Unix timestamp for when the server should refresh its registration.
            Only present if operation was successful
          format: double
          type: number
        server:
          $ref: "#/components/schemas/ServerResponse"
      required:
      - key
      - refresh_before
      - server
      type: object
    UpdateResponse:
      example:
        server:
          player_count: 5
          mods:
          - organization: organization
            name: name
            version: version
          - organization: organization
            name: name
            version: version
          unique_id: unique_id
          password_protected: true
          name: name
          description: description
          max_players: 5
          ports:
            game: 0
            a2s: 6
            ping: 1
          last_heartbeat: 2.3021358869347655
          is_verified: true
          current_map: current_map
        refresh_before: 0.8008281904610115
      properties:
        refresh_before:
          description: Unix timestamp for when the server should refresh its registration.
            Only present if operation was successful
          format: double
          type: number
        server:
          $ref: "#/components/schemas/ServerResponse"
      required:
      - refresh_before
      - server
      type: object
    Chivalry2Ports:
      example:
        game: 0
        a2s: 6
        ping: 1
      properties:
        game:
          description: The port number the server is running on
          format: int32
          type: integer
        a2s:
          description: The port number the server is responding to a2s requests at
          format: int32
          type: integer
        ping:
          description: The port number the server is accepting ping requests at
          format: int32
          type: integer
      required:
      - a2s
      - game
      - ping
      type: object
    StatusResponse:
      example:
        context: "{}"
        message: message
        status: status
      properties:
        status:
          description: The status code
          type: string
        message:
          description: A human readable message about the status
          type: string
        context:
          description: Optional context for the status
          type: object
      required:
      - message
      - status
      type: object
    BanStatusResponse:
      example:
        banned: true
      properties:
        banned:
          description: Whether the IP is banned
          type: boolean
      required:
      - banned
      type: object
    ErrorResponse:
      properties:
        status:
          description: The status code
          type: string
        message:
          description: A human readable message about the error
          type: string
        stack:
          description: Optional stack trace
          type: string
      required:
      - message
      - status
      type: object
    BanListResponse:
      example:
        banned_ips:
        - banned_ips
        - banned_ips
      properties:
        banned_ips:
          items:
            type: string
          type: array
      required:
      - banned_ips
      type: object
    VerifiedListResponse:
      example:
        verified_ips:
        - verified_ips
        - verified_ips
      properties:
        verified_ips:
          items:
            type: string
          type: array
      required:
      - verified_ips
      type: object
    IpListRequest:
      example:
        verified_ips:
        - verified_ips
        - verified_ips
        banned_ips:
        - banned_ips
        - banned_ips
      properties:
        banned_ips:
          items:
            type: string
          type: array
        verified_ips:
          items:
            type: string
          type: array
      type: object
    MotdRequest:
      example:
        Language: Language
      properties:
        Language:
          type: string
      type: object
    _api_playfab_Client_Matchmake_post_request:
      properties:
        LobbyId:
          type: string
      required:
      - LobbyId
      type: object

